name: Fetch Closed PRs and Output to CSV
 
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to fetch closed PRs from (repo)'
        required: true
        type: string
defaults:
  run:
    shell: bash
env:
    ORG_NAME: "openpitrix" 
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  fetch-closed-prs:
    runs-on: ubuntu-latest
 
    steps:
      - name: Install jq
        run: sudo apt update && sudo apt install -y jq
 
      - name: Fetch closed PRs via API and convert to CSV  
        run: |
          REPO="${{ github.event.inputs.repository }}"
          echo "Fetching closed PRs for repository: $REPO"
 
          # API Request to get closed PRs
          API_RESPONSE=$(curl -s -H "Accept: application/vnd.github.v3+json"\
               -H "Authorization: token $GH_TOKEN" \
               "https://api.github.com/repos/$ORG_NAME/$REPO/pulls?state=closed&per_page=100" )
          echo "https://api.github.com/repos/$ORG_NAME/$REPO/pulls?state=closed&per_page=100"
          # echo "GitHub API Response: $API_RESPONSE"

          PR_numbers=$(echo "$API_RESPONSE" | jq -r 'if type=="array" then .[] | .number  else empty end') 
          echo "PR_Number,Reviewer,Comment," > closed_prs.csv
          echo "$PR_numbers"
          for PR in $PR_numbers; do

            REVIEWS=$(curl -s -H "Accept: application/vnd.github.v3+json"\
                -H "Authorization: token $GH_TOKEN" \
                "https://api.github.com/repos/$ORG_NAME/$REPO/pulls/$PR/comments" )
            echo "Fecthing Review Comments for $PR #$REVIEWS"
            echo "$REVIEWS" | jq -r --arg PR "$PR" \
            '.[] | [$PR,.user.login,.body] | @csv' >> closed_prs.csv 
          done
          echo "Review Comments saved to closed_prs.csv"
 
      - name: Upload PR List as CSV Artifact
        uses: actions/upload-artifact@v4
        with:
          name: closed_prs_csv
          path: closed_prs.csv